version: '3.8'

volumes:
  db-data:

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    init: true
    command: npm run start:dev
    working_dir: /app
    depends_on:
      - mysql
    volumes:
      - .:/app
    ports:
      - '8080:8080'
      - '3900:3900'
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'shadowchat'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
