version: '3.8'

volumes:
  pg-data:

services:
  # node:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   init: true
  #   command: npm run start:dev
  #   working_dir: /app
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '8080:8080'
  #     - '3900:3900'
  postgres:
    image: postgres
    container_name: pg16
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    ports:
      - '5050:80'
    depends_on:
      - postgres